

kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job
      labels:
        app: batch-task
    spec:
      containers:
      - name: task-container
        image: busybox:latest
        command: ["sh", "-c", "echo hello welcome!!! && sleep 10" ]
      restartPolicy: Never
