
kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
   name: dev-pvc
   namespace: nginx 

spec:
   accessModes:
     - ReadWriteOnce

   resources:
     requests:
             storage: 1Gi
   storageClassName: example

