apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-pv
  namespace: oracle
  labels:
    app: oracle
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data

