apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: example

