
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: oracle-pvc
  namespace: oracle
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
